# Generated by Django 5.0.7 on 2024-07-16 11:33

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("user", "0002_alter_profile_image"),
    ]

    operations = [
        migrations.AlterField(
            model_name="profile",
            name="image",
            field=models.ImageField(default="avatar.jpg", upload_to="Profile_Images"),
        ),
    ]
